version: "3"
services:
  mongo:
    container_name: faturaflow_db
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: faturaflow
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    container_name: faturaflow_mongo_express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: common
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo

volumes:
  mongo_data:
